### PR TITLE
SvelteKit upgrade and Icon system change

### PR DESCRIPTION
**Pull request by AndrewLester**
## Status:

:rocket: Ready

## Description

Don't worry, haven't forgotten about #83. Recently @anyaparekh moved all project testimonials to the new testimonial content type, so a few more CSS changes and #83 will be good.

About this PR: Since a few devs are gonna take on some issues in this repo I thought it might be good to upgrade to the newest SvelteKit version, which makes writing page components and loading page data much simpler through the use of automatic type validation (no need to import or apply SvelteKit types). Type safety is still ensured via `svelte-check` as well as within VSCode.

EDIT: This PR also now removes the @svicons/boxicons-* dependencies and instead uses @iconify/svelte. @svicons no longer exists, and @iconify seems to be a reliable replacement.

### CODE REVIEW

**Comment by AndrewLester** [comment]
Looks like npm is down. I'll redeploy later.

**Review by arpanlaha — APPROVED** [review]
sweet

**Review by SirajChokshi — APPROVED** [review]

**Comment by AndrewLester** [comment]
Hm actually it looks like [@svicons/boxicons-regular](https://www.npmjs.com/package/@svicons/boxicons-regular) and the solid variant are gone from npm... so strange, the former was there at least in Feb from google cache. No info on the repo or on the maintainer's twitter... maybe I'll tweet at him and also consider some other options in the mean time.

**Comment by AndrewLester** [comment]
Just asked the maintainer about the library on twitter and he confirmed [it's gone](https://twitter.com/jrib_/status/1635670956378329092?s=20) (forever), so I've gone ahead and replaced @svicons usages with @iconify/svelte. This still works during SSR, so icons are prerendered, it just requires some additional code...

**Review by arpanlaha — APPROVED** [review]
sweet, thanks for tracking the icon issue down

**Comment by AndrewLester** [comment]
Merging to allow for new issue development, but open to change.

**Pull request merged**
