### PR TITLE
Better handle roles section title on students join page

### PR DESCRIPTION
**Pull request by AndrewLester**
## Status:

:rocket: Ready

## Description

More accurately handle "Role" section titles on students join page. There are three cases:
- A role is "open," which means it goes under a section with the title "Open Roles"
- A role is not open while another role is open, which means it goes under a section with the title "Other Roles"
- A role is not open when no other roles are open, which means it goes under a section with the title "Roles"

## Screenshots

image

image

### CODE REVIEW

**Comment by SirajChokshi** [comment]
Should we consider just not rendering positions that are not open?

Or at least having the second list (of "other roles") be designed a bit differently. Right now they look equally important and the headings are too close.

**Comment by AndrewLester** [comment]
> Should we consider just not rendering positions that are not open?

We could just not render them, but, since the student join page isn't just for people finding application steps/actively applying, I think it makes sense to provide basic role-related information here to be expanded upon in Notion. This way, people can learn what new members will be doing.

To be clear, I think Software dev and Product Designer will be the only roles always visible. If we're recruiting for an external director, for example, I imagine the role would appear in "Open Roles" until it's no longer being recruited for (then hidden by the "visible" attribute).

> Or at least having the second list (of "other roles") be designed a bit differently. Right now they look equally important and the headings are too close.

Yeah, the design of this second list could definitely be improved. Maybe rephrasing the section could help.
The sort for roles will put roles being recruited for on top.

Here's an idea:
image

**Comment by SirajChokshi** [comment]
**Apologies for being picky about this if this change is urgent, I'm giving feedback without a lot of context. I'll approve for now -- I trust your judgement 😄**

I'm not a fan of the Badge/Pill design -- in many cases (during recruiting season) `role.every(r => r.isOpen)` and all roles will have this badge.

Maybe we keep one list and just add an apply button to the open ones? I mocked it up below.

FAQS

**Review by SirajChokshi — APPROVED** [review]
lgtm (but also see my comment lol)

**Comment by AndrewLester** [comment]
No rush on this at all, and I just switched to the apply button system. There is some weird layout shift with the buttons on the preview deployment when refreshing, which I'm looking into.

EDIT: Fixed the layout shifting, which I think? was because I put the "Apply" link inside the accordion's button. This nesting is not supported and not accessible, so I guess it just renders, weird sometimes? Fixed either way, with a few more divs for the Accordion component.

**Pull request merged**
